name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22.0', '1.22.1', '1.22.2' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install libpact_ffi
        run: |
          go install github.com/pact-foundation/pact-go/v2@v2.0.4
          pact-go -l DEBUG install
      - name: Build
        run: go test -v -race ./...
