name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.21.9', '1.22.0', '1.22.1', '1.22.2' ]
        race-opt: [ 'true', 'false' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install libpact_ffi
        run: |
          go install github.com/pact-foundation/pact-go/v2@v2.0.4
          PACT_GO=$(command -v pact-go)
          sudo "$PACT_GO" -l DEBUG install
      - name: Build
        env:
          RACE_OPT: ${{ matrix.race }}
        run: |
          if [ "$RACE_OPT" == "true" ]; then
            go test -v -race ./...
          else 
            go test -v ./...
          fi